// frameworks/react/src/atoms/Spinner/Spinner.tsx
/**
 * DelvUI React Spinner Component
 * Loading indicator with multiple variants and sizes
 */

import React from 'react';
import clsx from 'clsx';
import { AtomProps } from '@delvui/core';
import styles from './Spinner.module.css';

export interface SpinnerProps {
  /** Size of the spinner */
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  
  /** Visual variant */
  variant?: 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger';
  
  /** Loading text for accessibility */
  label?: string;
  
  /** Custom CSS classes */
  className?: string;
  
  /** Test ID */
  testId?: string;
}

// Atomic Design Metadata
export const SpinnerAtom: AtomProps = {
  id: 'spinner',
  name: 'Spinner',
  level: 'atom',
  category: 'feedback',
  complexity: 1,
  dependencies: [],
  baseElement: 'div',
  version: '1.0.0',
  description: 'A loading indicator to show ongoing processes',
  tags: ['loading', 'progress', 'feedback'],
  
  variants: [
    {
      name: 'default',
      description: 'Default spinner',
      props: { size: 'md' },
      preview: '<Spinner />'
    },
    {
      name: 'small',
      description: 'Small spinner for buttons',
      props: { size: 'sm' },
      preview: '<Spinner size="sm" />'
    },
    {
      name: 'primary',
      description: 'Primary colored spinner',
      props: { variant: 'primary' },
      preview: '<Spinner variant="primary" />'
    }
  ]
};

/**
 * Spinner Component
 */
export const Spinner: React.FC<SpinnerProps> = ({
  size = 'md',
  variant = 'default',
  label = 'Loading...',
  className,
  testId = 'spinner'
}) => {
  const spinnerClasses = clsx([
    styles.spinner,
    styles[`size-${size}`],
    styles[`variant-${variant}`],
    className
  ]);

  return (
    <div
      className={spinnerClasses}
      role="status"
      aria-label={label}
      data-testid={testId}
      data-delvui-component="spinner"
      data-atomic-level="atom"
    >
      <div className={styles.circle} />
      <span className={styles.srOnly}>{label}</span>
    </div>
  );
};

Spinner.displayName = 'Spinner';

export default Spinner;

// frameworks/angular/src/atoms/Spinner/spinner.component.ts
/**
 * DelvUI Angular Spinner Component
 */

import { Component, Input, HostBinding, ViewEncapsulation, ChangeDetectionStrategy } from '@angular/core';
import { AtomProps } from '@delvui/core';

export type SpinnerSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type SpinnerVariant = 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger';

@Component({
  selector: 'delv-spinner',
  template: `
    <div class="spinner-circle"></div>
    <span class="sr-only">{{ label }}</span>
  `,
  styleUrls: ['./spinner.component.css'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'role': 'status',
    '[attr.aria-label]': 'label',
    '[attr.data-testid]': 'testId',
    '[attr.data-delvui-component]': '"spinner"',
    '[attr.data-atomic-level]': '"atom"'
  }
})
export class SpinnerComponent {
  @Input() size: SpinnerSize = 'md';
  @Input() variant: SpinnerVariant = 'default';
  @Input() label: string = 'Loading...';
  @Input() testId: string = 'spinner';

  @HostBinding('class')
  get hostClasses(): string {
    return [
      'delv-spinner',
      `delv-spinner--size-${this.size}`,
      `delv-spinner--variant-${this.variant}`
    ].join(' ');
  }

  static readonly atomMetadata: AtomProps = {
    id: 'spinner-angular',
    name: 'Spinner',
    level: 'atom',
    category: 'feedback',
    complexity: 1,
    dependencies: [],
    baseElement: 'div',
    version: '1.0.0',
    description: 'A loading indicator to show ongoing processes (Angular)',
    tags: ['loading', 'progress', 'feedback', 'angular']
  };
}
